{
    'name': 'Mini Sales Order System',
    'description': 'mini sales order system',
    'version': '1.0',
    'depends':['base','web'],
    'data':[
        "security/ir.model.access.csv",
        "views/order.xml",
        "views/order_line.xml",
        "views/delivery.xml",
        "views/invoice.xml",
        "views/quotation.xml",
        "views/payment.xml",
        "views/product.xml",
        "views/sequence.xml",
        "views/dashboard.xml",
        "views/customer.xml",
        "reports/sales_invoices_report.xml",
    ],
    'application':True,
    'installable':True,
}